### PR TITLE
Update Release Notes Script and Style

### PR DESCRIPTION
**Pull request by itisAliRH**
Follow-up on #12

### CODE REVIEW

**Review by davelopez — APPROVED** [review]

**Comment by davelopez** [comment]
Thanks @itisAliRH

**Comment by bgruening** [comment]
OO, why was this never merged? Is this still relevant?

**Comment by bgruening** [comment]
Please poke me/us if this gets not merged.

**Comment by itisAliRH** [comment]
@bgruening I can't recall why it didn't merge but the news webhook is removed in galaxyproject/galaxy#17675 and the PR is not relevant anymore. So, I'll close it.

**Pull request closed without merging**
